# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42d4a78dd775efeac8e69396b3c28816c6739c43723193be81da501072ed06ca181f595ced011641feec5cb6a72714453ae16b79e468fb2216247a22c1ea5cca

test:
  secret_key_base: f769d8f9c047105fa4a4218ee328ec349a646c4ca43f8820b950477ec88b46618b4a867d267158f3fd6b62e22f5921e08a614d315de07661f37957d72b3de334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
